baseURL: http://iminabar.com/
disablePathToLower: true
languageCode: en-us
title: Agustín Amenábar L. | CV – Résumé
theme: avicenna
assetDir: 'resources/assets'

params:
    home:
        title: 'CV – Résumé'
